# -*- coding: utf-8 -*-
"""programing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3VOqtg6rhBbFd0L3FhHSZmNtC8nGUzy
"""

#تجميل مكتبة Opem CV
!pip install opencv_python

# استخدام المكتبة
import cv2
from google.colab.patches import cv2_imshow

#إستدعاء صورة وحفظها بمتغير
image2=cv2.imread(r"//content/Kingdome Hearts.jpg")

# تغيير حجم الصورة
image2=cv2.resize(image2,(600,400))

#قلب الصورة أفقيا
image2=cv2.flip(image2,1)

#طباعة أبعاد الصورة
print(image2.shape)

#إضافة نص على الصورة "معسكرات هاش بلس هيا بنا"
image2=cv2.putText(image2,"Hush Plus",(250,150),cv2.FONT_HERSHEY_PLAIN,3,(208,50,239),4)
# (image2,"texet",(الإحداثيات),type text,(حجم الخط),( لون الخط),سمك النص)

#إضافة نص على الصورة "معسكرات هاش بلس هيا بنا"
image2=cv2.putText(image2,"Roaa Kalantan",(300,180),cv2.FONT_HERSHEY_PLAIN,1,(239,56,208),2)
# (image2,"texet",(الإحداثيات),type text,(حجم الخط),( لون الخط),سمك النص)

#رسم خط بكود المستطيل
image2=cv2.rectangle(image2,(170,120),(170,210),(255,0,130),2)
# تحريكه لليسار نطرح 40
image2=cv2.rectangle(image2,(130,120),(130,210),(224,130,0),2)
#  نقلب المستيل الأول أرقامه ونبدل x ,y ثم نحرك لليسار بطر x -10
image2=cv2.rectangle(image2,(210-15,180),(120-15,180),(24,230,0),2)

image2=cv2.rectangle(image2,(210-15,170-30),(120-15,170-30),(254,210,70),2)

# لعرض الصورة في المكتبةopen cv
cv2_imshow(image2)

